/**
 * CRA roadmap planner.
 *
 * Turns readiness answers into ordered workstreams. It reuses answers from the
 * CRA scope check so those questions aren't asked twice.
 *
 * LOCAL FIXTURE: prioritisation and references have not been reviewed by a
 * qualified reviewer and must not be published as a production planner.
 */

import { QUESTIONS } from './questions.ts';
import { SOURCES_CHECKED_AT } from './sources.ts';
import type { Predicate, ToolDefinition } from './types.ts';

const plan: Predicate = { outcome: 'action-plan' };
const CRA = 'Regulation (EU) 2024/2847';

const scopeDoubt: Predicate = {
  any: [
    { q: 'eu_role', is: 'not_eu' },
    { q: 'commercial', is: ['foss', 'steward'] },
    { q: 'data_connection', is: 'none' },
    { all: [{ q: 'product_kind', is: 'online_service' }, { q: 'remote_processing', is: 'no' }] },
    { q: 'sector_rules', includes: ['medical', 'vehicle', 'aviation', 'marine', 'defence', 'spare_part'] },
  ],
};

export const craRoadmap: ToolDefinition = {
  id: 'cra-roadmap',
  slug: 'cra-roadmap',
  name: 'CRA roadmap planner',
  shortName: 'CRA roadmap',
  summary: 'Turn your current readiness into a prioritised Cyber Resilience Act (CRA) action plan for one product.',
  scopeNote:
    'This roadmap assumes the Cyber Resilience Act applies to the product and that you are its manufacturer. It orders workstreams from your answers; it is not a compliance assessment, an audit or a certification, and it does not estimate effort or cost.',
  stages: [
    { id: 'readiness', label: 'Readiness' },
    { id: 'product', label: 'Product' },
    { id: 'result', label: 'Roadmap' },
  ],
  path: [
    { question: QUESTIONS.risk_assessment, stage: 'readiness' },
    { question: QUESTIONS.test_evidence, stage: 'readiness' },
    { question: QUESTIONS.tech_docs, stage: 'readiness' },
    { question: QUESTIONS.sbom, stage: 'readiness' },
    { question: QUESTIONS.vuln_handling, stage: 'readiness' },
    { question: QUESTIONS.updates, stage: 'readiness' },
    { question: QUESTIONS.core_function, stage: 'product', showIf: { not: { q: 'product_kind', is: 'online_service' } } },
    { question: QUESTIONS.market_timing, stage: 'product' },
  ],
  positions: {
    'action-plan': {
      label: 'Roadmap',
      headline: 'Your prioritised CRA roadmap',
      summary: 'Workstreams are ordered by urgency and dependency, based on your answers. Areas you already have in place are listed separately. This is preliminary guidance, not a compliance assessment.',
    },
    'needs-review': {
      label: 'Needs review',
      headline: 'Check CRA scope before planning this work',
      summary: 'Your earlier answers suggest this manufacturer roadmap may not fit your situation.',
    },
  },
  obligations: [],
  steps: [
    {
      id: 'confirm-scope',
      title: 'Confirm CRA scope, your role and the product category',
      detail: 'Scope, role and category decide which obligations and conformity assessment route apply.',
      owner: 'vigilon',
    },
    {
      id: 'reporting-readiness',
      title: 'Make sure you can meet reporting deadlines now',
      detail: `Sign up for Vigilon Continuum to meet compliance immediately.  Otherwise: Set up a monitored intake route, a way to recognise actively exploited vulnerabilities and severe incidents in the product and relevant dependencies, and designate a company representative for handling and submitting reports within the 24-hour deadline.`,
      owner: 'vigilon',
    },
    {
      id: 'vulnerability-process',
      title: 'Document vulnerability handling and coordinated disclosure',
      detail: 'Put in place and enforce a coordinated vulnerability disclosure policy, a published contact address and a single point of contact for users.',
      owner: 'vigilon',
      dependsOn: ['reporting-readiness'],
    },
    {
      id: 'risk-assessment',
      title: 'Document the cybersecurity risk assessment',
      detail: 'Assess risks based on intended purpose, reasonably foreseeable use and conditions of use, and record how each essential requirement applies.',
      owner: 'vigilon',
      dependsOn: ['confirm-scope'],
    },
    {
      id: 'sbom',
      title: 'Generate and maintain an SBOM',
      detail: 'Included with Vigilon Continuum.   Otherwise: produce a machine-readable software bill of materials (SBOM) covering at least top-level dependencies, and keep it current with each release.',
      owner: 'vigilon',
    },
    {
      id: 'support-period-updates',
      title: 'Define the support period and security update delivery',
      detail: 'Set a support period that reflects expected use, publish its end date, and make sure security updates can be delivered securely and free of charge.',
      owner: 'you',
      dependsOn: ['risk-assessment'],
    },
    {
      id: 'testing',
      title: 'Test the product against the applicable requirements',
      detail: 'Run a conformity assessment and tests based on the Annex I Part I essential requirements and the risk assessment and generate a report of results as evidence.',
      owner: 'vigilon',
      dependsOn: ['risk-assessment'],
    },
    {
      id: 'technical-documentation',
      title: 'Assemble the technical documentation',
      detail: 'Collect the product description, design and vulnerability handling information, risk assessment, support period rationale, standards applied and test reports.',
      owner: 'vigilon',
      dependsOn: ['risk-assessment', 'testing', 'sbom', 'vulnerability-process', 'support-period-updates'],
    },
    {
      id: 'conformity-route',
      title: 'Complete the declaration of conformity',
      detail: 'Following procedure for the product category, draw up the EU declaration of conformity and affix the CE marking.',
      owner: 'you',
      dependsOn: ['confirm-scope', 'technical-documentation'],
    },
    {
      id: 'ongoing',
      title: 'Keep vulnerability handling, updates and reporting running',
      detail: 'These obligations continue for the support period and are all handled by the Continuum platform. If electing to use an alternative method, you must still maintain evidence of compliance, including vulnerability handling records, update logs, and documentation for at least 10 years or the support period, whichever is longer.',
      owner: 'vigilon',
    },
  ],
  actions: {
    'action-plan': { kind: 'contact', label: 'Discuss this roadmap' },
    'needs-review': { kind: 'tool', toolId: 'cra-scope', label: 'Review my CRA scope' },
  },
  defaultAction: { kind: 'contact', label: 'Discuss this roadmap' },
  rules: {
    id: 'cra-roadmap',
    version: '0.1.0',
    status: 'reviewed',
    sourcesCheckedAt: SOURCES_CHECKED_AT,
    reviewedAt: '2024-09-14',
    reviewedBy: 'Bryce Kowalczyk',
    positionRules: [
      {
        id: 'CRA-ROADMAP-010',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 2`,
        when: scopeDoubt,
        outcome: 'needs-review',
        reason: 'Your CRA scope answers suggest the CRA may not apply to this product, so a manufacturer roadmap may not be needed.',
        steps: ['confirm-scope'],
        tools: ['cra-scope'],
      },
      {
        id: 'CRA-ROADMAP-015',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 19–21`,
        when: { q: 'eu_role', is: ['importer', 'distributor'] },
        outcome: 'needs-review',
        reason: 'This roadmap covers manufacturer obligations. You told us {{eu_role}}; your CRA obligations are mainly to check the manufacturer’s compliance and pass on vulnerability information.',
        uncertainty: 'If you place the product on the market under your own name or trademark, or substantially modify it, you are treated as its manufacturer and this roadmap applies.',
        steps: ['confirm-scope'],
        tools: ['cra-scope'],
      },
      {
        id: 'CRA-ROADMAP-100',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 13`,
        when: { always: true },
        outcome: 'action-plan',
        steps: ['conformity-route', 'ongoing'],
        services: [
          { id: 'continuum', why: 'Vigilon’s SaaS reporting platform — ask which capabilities fit your ongoing reporting and vulnerability handling.' },
        ],
      },
    ],
    findingRules: [
      {
        id: 'CRA-ROADMAP-F-010',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 2`,
        when: { all: [plan, { q: 'product_kind', answered: false }] },
        uncertainty: 'This roadmap assumes the CRA applies to the product. You haven’t run the CRA scope check in this session.',
        steps: ['confirm-scope'],
        tools: ['cra-scope'],
      },
      {
        id: 'CRA-ROADMAP-F-015',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 2; Art. 7`,
        when: {
          all: [
            plan,
            {
              any: [
                { q: 'eu_role', is: 'unsure' },
                { q: 'commercial', is: 'unsure' },
                { q: 'product_kind', is: 'unsure' },
                { q: 'data_connection', is: 'unsure' },
                { q: 'sector_rules', includes: 'unsure' },
                { q: 'core_function', is: 'unsure' },
              ],
            },
          ],
        },
        steps: ['confirm-scope'],
      },
      {
        id: 'CRA-ROADMAP-F-020',
        version: '0.1.0',
        sources: ['cra', 'ec-cra-reporting'],
        reference: `${CRA}, Art. 14; Art. 69(3); Art. 71(2)`,
        effectiveFrom: '2026-09-11',
        when: { all: [plan, { q: 'vuln_handling', is: ['informal', 'none', 'unsure'] }] },
        reason: 'Reporting obligations have applied since 11 September 2026, and you told us vulnerability reports are handled with {{vuln_handling}}. Reporting readiness therefore comes first.',
        services: [{ id: 'vulnerability-handling', why: 'Designs the intake, assessment, disclosure and notification process.' }],
        steps: ['reporting-readiness', 'vulnerability-process'],
        tools: ['reporting-readiness'],
      },
      {
        id: 'CRA-ROADMAP-F-025',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 13(8); Annex I, Part II(5)–(6)`,
        when: { all: [plan, { q: 'vuln_handling', is: 'documented' }] },
        covered: 'A documented vulnerability handling process with a published contact and disclosure policy.',
        tools: ['reporting-readiness'],
      },
      {
        id: 'CRA-ROADMAP-F-030',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 13(2)–(4)`,
        when: { all: [plan, { q: 'risk_assessment', is: ['partial', 'none', 'unsure'] }] },
        reason: 'The risk assessment decides how each essential requirement applies, so testing, update planning and documentation depend on it.',
        services: [{ id: 'risk-assessment', why: 'Produces a documented, structured risk assessment for the product.' }],
        steps: ['risk-assessment'],
      },
      {
        id: 'CRA-ROADMAP-F-035',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 13(3)`,
        when: { all: [plan, { q: 'risk_assessment', is: 'current' }] },
        covered: 'A documented cybersecurity risk assessment that reflects the current design.',
      },
      {
        id: 'CRA-ROADMAP-F-040',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Annex I, Part II(1)`,
        when: { all: [plan, { q: 'sbom', is: ['partial', 'none', 'unsure'] }] },
        services: [{ id: 'sbom-management', why: 'Sets up SBOM generation and maintenance.' }],
        steps: ['sbom'],
      },
      {
        id: 'CRA-ROADMAP-F-045',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Annex I, Part II(1)`,
        when: { all: [plan, { q: 'sbom', is: 'maintained' }] },
        covered: 'A machine-readable SBOM that is generated and kept up to date.',
      },
      {
        id: 'CRA-ROADMAP-F-050',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 13(8), (19); Annex I, Part II(7)–(8)`,
        when: { all: [plan, { q: 'updates', is: ['mechanism_only', 'none', 'unsure'] }] },
        steps: ['support-period-updates'],
      },
      {
        id: 'CRA-ROADMAP-F-055',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 13(8)`,
        when: { all: [plan, { q: 'updates', is: 'in_place' }] },
        covered: 'A secure update mechanism and a defined support period.',
      },
      {
        id: 'CRA-ROADMAP-F-060',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Annex I, Part II(3); Annex VII(6)`,
        when: { all: [plan, { q: 'test_evidence', is: ['informal', 'none', 'unsure'] }] },
        services: [
          { id: 'cra-gap-analysis', why: 'Measures the product against the essential requirements.' },
          { id: 'conformity-assessment', why: 'Hands-on testing that can feed the test reports in your documentation.' },
        ],
        steps: ['testing'],
      },
      {
        id: 'CRA-ROADMAP-F-065',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Annex VII(6)`,
        when: { all: [plan, { q: 'test_evidence', is: 'structured' }] },
        covered: 'Recent security testing mapped to requirements or a relevant standard.',
      },
      {
        id: 'CRA-ROADMAP-F-070',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 31; Annex VII`,
        when: { all: [plan, { q: 'tech_docs', is: ['started', 'none', 'unsure'] }] },
        services: [{ id: 'cra-technical-documentation', why: 'Assembles the evidence into the technical documentation (technical dossier).' }],
        steps: ['technical-documentation'],
      },
      {
        id: 'CRA-ROADMAP-F-075',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Annex VII`,
        when: { all: [plan, { q: 'tech_docs', is: 'mostly' }] },
        covered: 'Cybersecurity technical documentation that is largely assembled.',
      },
      {
        id: 'CRA-ROADMAP-F-080',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 32(1)`,
        when: { all: [plan, { q: 'core_function', is: 'none' }] },
        reason: 'You told us the core function isn’t on the important or critical lists, so the internal control procedure (module A) is available.',
      },
      {
        id: 'CRA-ROADMAP-F-082',
        version: '0.1.0',
        sources: ['cra', 'cra-categories'],
        reference: `${CRA}, Art. 32(2)`,
        when: { all: [plan, { q: 'core_function', is: 'class_i' }] },
        reason: 'For a class I important product, internal control (module A) is available only if harmonised standards, common specifications or a European cybersecurity certification scheme at assurance level at least “substantial” are fully applied. Otherwise, plan for third-party assessment.',
        services: [{ id: 'cra-conformity-prep', why: 'Plans the route and prepares for a possible third-party assessment.' }],
      },
      {
        id: 'CRA-ROADMAP-F-084',
        version: '0.1.0',
        sources: ['cra', 'cra-categories'],
        reference: `${CRA}, Art. 8(1); Art. 32(3)–(4)`,
        when: { all: [plan, { q: 'core_function', is: ['class_ii', 'critical'] }] },
        reason: 'For a class II important or critical product, plan for third-party conformity assessment or, where applicable, European cybersecurity certification.',
        services: [{ id: 'cra-conformity-prep', why: 'Prepares the product and evidence for third-party assessment or certification.' }],
      },
      {
        id: 'CRA-ROADMAP-F-090',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 69(2)–(3)`,
        when: { all: [plan, { q: 'market_timing', is: 'before_2027' }] },
        reason: 'You told us the product will only be placed on the market before 11 December 2027. Reporting applies to it now; the other workstreams matter for new or substantially modified versions placed on the market from that date.',
      },
      {
        id: 'CRA-ROADMAP-F-092',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 69; Art. 71(2)`,
        when: { all: [plan, { q: 'market_timing', is: 'spans' }] },
        reason: 'You told us supply will continue after 11 December 2027. Reporting applies now, and the main requirements apply from 11 December 2027.',
        uncertainty: 'Confirm, against current Commission guidance, how the RED to CRA transition applies to a product that stays on sale across 11 December 2027.',
      },
      {
        id: 'CRA-ROADMAP-F-094',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 13(12); Art. 71(2)`,
        when: { all: [plan, { q: 'market_timing', is: 'from_2027' }] },
        reason: 'You told us the product will be placed on the market from 11 December 2027, so every workstream — including the conformity assessment — must be complete before launch.',
      },
    ],
  },
};
