/**
 * CRA scope check.
 *
 * LOCAL FIXTURE: these rules implement the cited provisions of Regulation
 * (EU) 2024/2847 as read on the sources-checked date. They have not been
 * reviewed by a qualified reviewer and must not be published as a production
 * checker until `status` is `reviewed` with a named reviewer.
 */

import { QUESTIONS } from './questions.ts';
import { SOURCES_CHECKED_AT } from './sources.ts';
import type { Predicate, ToolDefinition } from './types.ts';

const notEu: Predicate = { q: 'eu_role', is: 'not_eu' };
const notCommercial: Predicate = { q: 'commercial', is: ['foss', 'steward'] };
const stopEarly: Predicate = { any: [notEu, notCommercial] };
const onlineService: Predicate = { q: 'product_kind', is: 'online_service' };
const noConnection: Predicate = { q: 'data_connection', is: 'none' };
const unrelatedService: Predicate = { all: [onlineService, { q: 'remote_processing', is: 'no' }] };
const internetConnected: Predicate = { q: 'internet', is: ['direct', 'via_device'] };
const excludedSector: Predicate = { q: 'sector_rules', includes: ['medical', 'vehicle', 'aviation', 'marine', 'defence', 'spare_part'] };
const isManufacturer: Predicate = { q: 'eu_role', is: 'manufacturer' };
const inScope: Predicate = { outcome: 'in-scope' };

const CRA = 'Regulation (EU) 2024/2847';

export const craScope: ToolDefinition = {
  id: 'cra-scope',
  slug: 'cra-scope',
  name: 'CRA scope check',
  shortName: 'CRA scope',
  summary: 'Check how your product, market and role affect whether the Cyber Resilience Act (CRA) is likely to apply.',
  scopeNote:
    'This check looks at the scope of the Cyber Resilience Act (Regulation (EU) 2024/2847) for one product or product family. It is preliminary guidance, not a legal determination or certification, and it does not assess other EU legislation.',
  stages: [
    { id: 'role', label: 'Role' },
    { id: 'product', label: 'Product' },
    { id: 'timing', label: 'Timing' },
    { id: 'result', label: 'Result' },
  ],
  path: [
    { question: QUESTIONS.eu_role, stage: 'role' },
    { question: QUESTIONS.commercial, stage: 'role', showIf: isManufacturer },
    { question: QUESTIONS.product_kind, stage: 'product', showIf: { not: stopEarly } },
    {
      question: QUESTIONS.data_connection,
      stage: 'product',
      showIf: { all: [{ not: stopEarly }, { not: onlineService }, { not: internetConnected }] },
    },
    { question: QUESTIONS.remote_processing, stage: 'product', showIf: { all: [{ not: stopEarly }, { not: noConnection }] } },
    {
      question: QUESTIONS.sector_rules,
      stage: 'product',
      showIf: { not: { any: [stopEarly, noConnection, unrelatedService] } },
    },
    {
      question: QUESTIONS.core_function,
      stage: 'product',
      showIf: { not: { any: [stopEarly, noConnection, onlineService, excludedSector] } },
    },
    {
      question: QUESTIONS.market_timing,
      stage: 'timing',
      showIf: { not: { any: [stopEarly, noConnection, unrelatedService, excludedSector] } },
    },
  ],
  positions: {
    'in-scope': {
      label: 'Likely in scope',
      headline: 'The CRA is likely to apply to this product',
      summary: 'Based on your answers, the product appears to fall within the Cyber Resilience Act. This is preliminary guidance, not a legal determination.',
    },
    'outside-checked-scope': {
      label: 'Likely outside the checked scope',
      headline: 'The CRA is likely not to apply, based on your answers',
      summary: 'This reflects the CRA scope checks in this tool only. Other EU legislation may still apply to the product.',
    },
    'needs-review': {
      label: 'Needs review',
      headline: 'Your answers need a specialist review',
      summary: 'At least one fact that decides CRA scope is uncertain, or falls outside what this tool checks.',
    },
  },
  obligations: [
    {
      id: 'essential-requirements',
      title: 'Essential cybersecurity requirements',
      detail: 'Design, develop and produce the product to meet the essential cybersecurity requirements, based on a documented cybersecurity risk assessment.',
      reference: `${CRA}, Art. 13(1)–(3); Annex I, Part I`,
    },
    {
      id: 'vulnerability-handling',
      title: 'Vulnerability handling during the support period',
      detail: 'Handle vulnerabilities in the product and its components — including a software bill of materials, a coordinated vulnerability disclosure policy and free security updates — for a support period of at least five years, unless the product is expected to be in use for less time.',
      reference: `${CRA}, Art. 13(8); Annex I, Part II`,
    },
    {
      id: 'reporting',
      title: 'Reporting — applies since 11 September 2026',
      detail: 'Notify actively exploited vulnerabilities and severe incidents through the Single Reporting Platform: an early warning within 24 hours, a notification within 72 hours, and a final report.',
      reference: `${CRA}, Art. 14; Art. 71(2)`,
    },
    {
      id: 'technical-documentation',
      title: 'Technical documentation',
      detail: 'Draw up the technical documentation before placing the product on the market, and keep it for at least 10 years or for the support period, whichever is longer.',
      reference: `${CRA}, Art. 13(12)–(13); Art. 31; Annex VII`,
    },
    {
      id: 'conformity-assessment',
      title: 'Conformity assessment, EU declaration of conformity and CE marking',
      detail: 'Carry out the conformity assessment procedure that applies to the product, then draw up the EU declaration of conformity and affix the CE marking.',
      reference: `${CRA}, Art. 13(12); Art. 32`,
    },
    {
      id: 'user-information',
      title: 'Information for users',
      detail: 'Provide contact details, a single point of contact for vulnerability reports, user information and instructions, and the end date of the support period.',
      reference: `${CRA}, Art. 13(16)–(19); Annex II`,
    },
    {
      id: 'importer-checks',
      title: 'Importer checks',
      detail: 'Before placing the product on the market, make sure the manufacturer carried out the conformity assessment and drew up the technical documentation, and that the product has CE marking, the EU declaration of conformity and user information. Tell the manufacturer about vulnerabilities you become aware of.',
      reference: `${CRA}, Art. 19`,
    },
    {
      id: 'distributor-checks',
      title: 'Distributor due care',
      detail: 'Before making the product available, verify the CE marking and that the manufacturer and importer have provided the required information and documents. Tell the manufacturer about vulnerabilities you become aware of.',
      reference: `${CRA}, Art. 20`,
    },
  ],
  steps: [
    {
      id: 'resolve-open-questions',
      title: 'Resolve the open questions',
      detail: 'Confirm the uncertain facts listed above with your compliance lead or a specialist, then run this check again.',
      owner: 'you',
    },
    {
      id: 'check-reporting',
      title: 'Check your reporting readiness',
      detail: 'Reporting obligations already apply. Make sure you could send a 24-hour early warning.',
      owner: 'you',
    },
    {
      id: 'confirm-category',
      title: 'Confirm the product category',
      detail: 'Compare the core function with the technical descriptions of important and critical products. The category decides the conformity assessment route.',
      owner: 'you',
      dependsOn: ['resolve-open-questions'],
    },
    {
      id: 'build-roadmap',
      title: 'Build a prioritised CRA roadmap',
      detail: 'Turn the obligations above into workstreams, starting with those your current readiness leaves open.',
      owner: 'you',
      dependsOn: ['resolve-open-questions', 'confirm-category'],
    },
    {
      id: 'gap-analysis',
      title: 'Assess gaps against the essential requirements',
      detail: 'Compare the product and your processes with the CRA requirements to size the work.',
      owner: 'vigilon',
      dependsOn: ['build-roadmap'],
    },
    {
      id: 'request-evidence',
      title: 'Ask the manufacturer for conformity evidence',
      detail: 'Request the EU declaration of conformity and confirmation of the conformity assessment and technical documentation, and agree how you will pass on vulnerability information.',
      owner: 'you',
    },
    {
      id: 'confirm-other-legislation',
      title: 'Confirm the legislation that applies instead',
      detail: 'Check the product’s classification under the other rules you selected, including their own cybersecurity requirements.',
      owner: 'you',
    },
    {
      id: 'recheck-on-change',
      title: 'Check again if your plans change',
      detail: 'A change in how the product is supplied, connected or monetised can change this result.',
      owner: 'you',
    },
  ],
  actions: {
    'in-scope': { kind: 'tool', toolId: 'cra-roadmap', label: 'Build my CRA roadmap' },
    'needs-review': { kind: 'contact', label: 'Discuss these open questions' },
    'outside-checked-scope': { kind: 'contact', label: 'Talk to an expert' },
  },
  defaultAction: { kind: 'contact', label: 'Talk to an expert' },
  rules: {
    id: 'cra-scope',
    version: '0.1.0',
    status: 'fixture',
    sourcesCheckedAt: SOURCES_CHECKED_AT,
    reviewedAt: null,
    reviewedBy: null,
    positionRules: [
      {
        id: 'CRA-SCOPE-010',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 2(1); Art. 3(22)`,
        when: notEu,
        outcome: 'outside-checked-scope',
        reason: 'You told us the product won’t be supplied in the EU. The CRA applies to products with digital elements made available on the EU market.',
        uncertainty: 'If you later supply the product in the EU, directly or through others, check again.',
        steps: ['recheck-on-change'],
      },
      {
        id: 'CRA-SCOPE-020',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Recitals 15 and 18; Art. 3(22)`,
        when: { q: 'commercial', is: 'foss' },
        outcome: 'outside-checked-scope',
        reason: 'You told us the product is free and open-source software that you don’t monetise. The CRA does not treat providing such software as a commercial activity.',
        uncertainty: 'This depends on how the software is supplied. For example, charging for technical support beyond cost recovery, or monetising the software through a platform or other services, can make supply commercial. Manufacturers who integrate your software must still exercise due diligence.',
        steps: ['recheck-on-change'],
      },
      {
        id: 'CRA-SCOPE-025',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 3(14); Art. 24`,
        when: { q: 'commercial', is: 'steward' },
        outcome: 'needs-review',
        reason: 'You told us you sustain open-source software intended for commercial use. The CRA sets a separate, lighter regime for open-source software stewards, including a documented cybersecurity policy and cooperation with market surveillance authorities.',
        uncertainty: 'Whether you qualify as an open-source software steward, and which reporting obligations apply to you, depends on your role in development. This tool does not assess the steward regime in detail.',
        services: [{ id: 'expert-call', why: 'Talk through whether the steward regime fits your organisation.' }],
        steps: ['resolve-open-questions'],
      },
      {
        id: 'CRA-SCOPE-030',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 2(2)–(4)`,
        when: { q: 'sector_rules', includes: ['medical', 'vehicle', 'aviation', 'marine'] },
        outcome: 'outside-checked-scope',
        reason: 'You told us {{sector_rules}} applies. The CRA does not apply to products covered by the medical device, in vitro diagnostic medical device or motor vehicle type-approval regulations, to products certified under the civil aviation regulation, or to equipment within the scope of the marine equipment directive.',
        uncertainty: 'These exclusions depend on that legislation actually applying to the product — for civil aviation, on the product being certified under it. Confirm the classification before relying on this result.',
        steps: ['confirm-other-legislation'],
      },
      {
        id: 'CRA-SCOPE-032',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 2(7)`,
        when: { q: 'sector_rules', includes: 'defence' },
        outcome: 'outside-checked-scope',
        reason: 'You told us the product is developed only for national security or defence, or to process classified information. The CRA does not apply to such products.',
        uncertainty: 'The exclusion covers products developed or modified exclusively for these purposes. Dual-use or commercially available versions need separate consideration.',
        steps: ['confirm-other-legislation'],
      },
      {
        id: 'CRA-SCOPE-034',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 2(6)`,
        when: { q: 'sector_rules', includes: 'spare_part' },
        outcome: 'outside-checked-scope',
        reason: 'You told us the product is a spare part replacing an identical component, made to the same specifications. The CRA does not apply to such spare parts.',
        uncertainty: 'This applies only to identical replacement components made to the same specifications. The product the part goes into remains subject to the CRA.',
        steps: ['recheck-on-change'],
      },
      {
        id: 'CRA-SCOPE-040',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 2(1); Art. 3(8)–(10)`,
        when: noConnection,
        outcome: 'outside-checked-scope',
        reason: 'You told us the product has no data connection of any kind. The CRA covers products whose intended purpose or reasonably foreseeable use includes a direct or indirect logical or physical data connection to a device or network.',
        uncertainty: 'Service, debug and update interfaces count, and so does reasonably foreseeable use. Check these before relying on this result.',
        steps: ['recheck-on-change'],
      },
      {
        id: 'CRA-SCOPE-045',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 3(2); Recitals 11–12`,
        when: unrelatedService,
        outcome: 'outside-checked-scope',
        reason: 'You told us you supply an online service only, and no product you supply relies on it. The CRA covers cloud services only as remote data processing needed for a product’s functions; websites that don’t support a product’s functionality are outside its scope. Cloud service models such as software as a service are addressed by the NIS2 Directive (EU) 2022/2555 instead.',
        uncertainty: 'If a manufacturer’s product needs your service for one of its functions, the service may be covered as part of that product. This tool does not assess NIS2.',
        steps: ['recheck-on-change'],
      },
      {
        id: 'CRA-SCOPE-050',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 3(1)–(2); Recital 11`,
        when: { all: [onlineService, { q: 'remote_processing', is: 'yes' }] },
        outcome: 'needs-review',
        reason: 'You told us you supply an online service that a product relies on. Remote data processing designed by or under the responsibility of a product’s manufacturer, and needed for one of the product’s functions, is part of that product under the CRA.',
        uncertainty: 'Responsibility depends on whose product it is and on whose behalf the service was developed. Agree with the product’s manufacturer how obligations are split.',
        services: [{ id: 'expert-call', why: 'Work out how CRA responsibilities are split between you and the product manufacturer.' }],
        steps: ['resolve-open-questions'],
      },
      {
        id: 'CRA-SCOPE-060',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 2`,
        when: {
          any: [
            { q: 'eu_role', is: 'unsure' },
            { q: 'commercial', is: 'unsure' },
            { q: 'product_kind', is: 'unsure' },
            { q: 'data_connection', is: 'unsure' },
            { q: 'remote_processing', is: 'unsure' },
            { q: 'sector_rules', includes: 'unsure' },
          ],
        },
        outcome: 'needs-review',
        reason: 'At least one answer that decides whether the CRA applies was “I’m not sure”, so this check can’t indicate a likely position yet.',
        services: [{ id: 'expert-call', why: 'Resolve the uncertain facts with a specialist.' }],
        steps: ['resolve-open-questions'],
      },
      {
        id: 'CRA-SCOPE-100',
        version: '0.1.0',
        sources: ['cra', 'ec-cra-summary'],
        reference: `${CRA}, Art. 2(1); Art. 3(1), (22)`,
        when: {
          all: [
            { q: 'eu_role', is: ['manufacturer', 'importer', 'distributor'] },
            { q: 'product_kind', is: ['hardware', 'software', 'component'] },
            { any: [internetConnected, { q: 'data_connection', is: ['direct', 'indirect'] }] },
            { not: { q: 'commercial', is: ['foss', 'steward', 'unsure'] } },
          ],
        },
        outcome: 'in-scope',
        reason: 'You told us you supply {{product_kind}}, that it can connect to a device or network, and that it is supplied in the EU. That matches the CRA’s scope: products with digital elements made available on the EU market with a direct or indirect data connection.',
      },
      {
        id: 'CRA-SCOPE-999',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 2`,
        when: { always: true },
        outcome: 'needs-review',
        reason: 'This combination of answers isn’t covered by the checks in this tool, so it needs a specialist review.',
        services: [{ id: 'expert-call', why: 'Review the facts this tool can’t assess.' }],
        steps: ['resolve-open-questions'],
      },
    ],
    findingRules: [
      {
        id: 'CRA-SCOPE-F-010',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 3(22); Recital 15`,
        when: { all: [inScope, { q: 'commercial', is: 'free' }] },
        uncertainty: 'You told us the product is free of charge. Supply in the course of a commercial activity can include free products — for example where related services or data are monetised. Confirm how the product is supplied.',
      },
      {
        id: 'CRA-SCOPE-F-020',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 13; Art. 14`,
        when: { all: [inScope, isManufacturer] },
        reason: 'As the manufacturer, you carry the main CRA obligations: meeting the essential cybersecurity requirements, handling vulnerabilities through a support period, reporting, and technical documentation with a conformity assessment.',
        obligations: [
          'essential-requirements',
          'vulnerability-handling',
          'reporting',
          'technical-documentation',
          'conformity-assessment',
          'user-information',
        ],
        services: [{ id: 'cra-gap-analysis', why: 'Shows where the product and your processes fall short of the requirements before you plan the work.' }],
        steps: ['build-roadmap', 'gap-analysis'],
        tools: ['cra-roadmap'],
      },
      {
        id: 'CRA-SCOPE-F-030',
        version: '0.1.0',
        sources: ['cra', 'ec-cra-reporting'],
        reference: `${CRA}, Art. 14; Art. 69(3); Art. 71(2)`,
        effectiveFrom: '2026-09-11',
        when: { all: [inScope, isManufacturer] },
        reason: 'Reporting obligations already apply. Since 11 September 2026, manufacturers must notify actively exploited vulnerabilities and severe incidents through the Single Reporting Platform — including for products placed on the market before 11 December 2027.',
        services: [
          { id: 'vulnerability-handling', why: 'Sets up the intake, assessment and notification process that reporting depends on.' },
          { id: 'continuum', why: 'Vigilon’s SaaS reporting platform — ask which capabilities fit your reporting process.' },
        ],
        steps: ['check-reporting'],
        tools: ['reporting-readiness'],
      },
      {
        id: 'CRA-SCOPE-F-040',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 19; Art. 21`,
        when: { all: [inScope, { q: 'eu_role', is: 'importer' }] },
        reason: 'As an importer, you may place the product on the market only if the manufacturer has met the CRA requirements, and you must pass on vulnerabilities you become aware of.',
        uncertainty: 'If you place the product on the market under your own name or trademark, or substantially modify it, you are treated as its manufacturer.',
        obligations: ['importer-checks', 'reporting'],
        services: [{ id: 'expert-call', why: 'Agree what evidence to request from the manufacturer.' }],
        steps: ['request-evidence', 'check-reporting'],
      },
      {
        id: 'CRA-SCOPE-F-045',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 20; Art. 21`,
        when: { all: [inScope, { q: 'eu_role', is: 'distributor' }] },
        reason: 'As a distributor, you must act with due care: verify the CE marking and required information before making the product available, and pass on vulnerabilities you become aware of.',
        uncertainty: 'If you place the product on the market under your own name or trademark, or substantially modify it, you are treated as its manufacturer.',
        obligations: ['distributor-checks'],
        services: [{ id: 'expert-call', why: 'Agree what evidence to request from the manufacturer or importer.' }],
        steps: ['request-evidence'],
      },
      {
        id: 'CRA-SCOPE-F-050',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 3(1)–(2)`,
        when: { all: [inScope, { q: 'remote_processing', is: 'yes' }] },
        reason: 'You told us the product relies on a remote service you develop or commission. That remote data processing is part of the product, so it must meet the CRA requirements too.',
      },
      {
        id: 'CRA-SCOPE-F-060',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 69(2)–(3)`,
        when: { all: [inScope, isManufacturer, { q: 'market_timing', is: 'before_2027' }] },
        reason: 'You told us the product will only be placed on the market before 11 December 2027. Such products become subject to the main CRA requirements only if they are substantially modified from that date — but the reporting obligations apply to them now.',
      },
      {
        id: 'CRA-SCOPE-F-062',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 69; Art. 71(2)`,
        when: { all: [inScope, isManufacturer, { q: 'market_timing', is: 'spans' }] },
        reason: 'You told us the product will be on the market before and after 11 December 2027. Reporting obligations apply now, and the main requirements apply from 11 December 2027.',
        uncertainty: 'Confirm, against current Commission guidance, how the transition applies to a product that stays on sale across 11 December 2027.',
      },
      {
        id: 'CRA-SCOPE-F-064',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 13(12); Art. 71(2)`,
        when: { all: [inScope, isManufacturer, { q: 'market_timing', is: 'from_2027' }] },
        reason: 'You told us the product will be placed on the market from 11 December 2027. Before then, it will need to meet the CRA requirements, complete the conformity assessment and carry the CE marking.',
      },
      {
        id: 'CRA-SCOPE-F-070',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 32(1)`,
        when: { all: [inScope, isManufacturer, { q: 'core_function', is: 'none' }] },
        reason: 'You told us the core function isn’t on the important or critical lists, so the internal control procedure (module A) is available for the conformity assessment.',
      },
      {
        id: 'CRA-SCOPE-F-072',
        version: '0.1.0',
        sources: ['cra', 'cra-categories'],
        reference: `${CRA}, Art. 7(1); Art. 32(2)`,
        when: { all: [inScope, isManufacturer, { q: 'core_function', is: 'class_i' }] },
        reason: 'You told us the core function is on the class I list of important products. Internal control (module A) is available only if you fully apply harmonised standards, common specifications or a European cybersecurity certification scheme at assurance level at least “substantial”. Otherwise, a third-party procedure (module B with C, or module H) is required.',
        services: [{ id: 'cra-conformity-prep', why: 'Plans the assessment route and prepares evidence for a possible third-party assessment.' }],
        steps: ['confirm-category'],
      },
      {
        id: 'CRA-SCOPE-F-074',
        version: '0.1.0',
        sources: ['cra', 'cra-categories'],
        reference: `${CRA}, Art. 7(1); Art. 32(3)`,
        when: { all: [inScope, isManufacturer, { q: 'core_function', is: 'class_ii' }] },
        reason: 'You told us the core function is on the class II list of important products. Conformity must be demonstrated through a third-party procedure (module B with C, or module H) or, where available, a European cybersecurity certification scheme at assurance level at least “substantial”.',
        services: [{ id: 'cra-conformity-prep', why: 'Prepares the product and evidence for third-party assessment.' }],
        steps: ['confirm-category'],
      },
      {
        id: 'CRA-SCOPE-F-076',
        version: '0.1.0',
        sources: ['cra', 'cra-categories'],
        reference: `${CRA}, Art. 8(1); Art. 32(4)`,
        when: { all: [inScope, isManufacturer, { q: 'core_function', is: 'critical' }] },
        reason: 'You told us the core function is on the critical products list. A European cybersecurity certificate may be required where the Commission has specified this by delegated act; otherwise, the class II procedures apply.',
        uncertainty: 'Check whether a delegated act requiring certification has been adopted for this product category.',
        services: [{ id: 'cra-conformity-prep', why: 'Prepares the product and evidence for certification or third-party assessment.' }],
        steps: ['confirm-category'],
      },
      {
        id: 'CRA-SCOPE-F-080',
        version: '0.1.0',
        sources: ['cra', 'red-da-repeal'],
        reference: 'Delegated Regulation (EU) 2022/30; Delegated Regulation (EU) 2026/339, Art. 1',
        when: {
          all: [
            inScope,
            { q: 'product_kind', is: 'hardware' },
            { not: { q: 'radio', is: 'no' } },
            { not: { q: 'market_timing', is: 'from_2027' } },
          ],
        },
        reason: 'If the product has radio functions, the RED cybersecurity requirements may also apply to it until they are repealed on 11 December 2027.',
        tools: ['red-scope'],
      },
      {
        id: 'CRA-SCOPE-F-090',
        version: '0.1.0',
        sources: ['cra'],
        reference: `${CRA}, Art. 2`,
        when: { q: 'sector_rules', includes: 'toll' },
        uncertainty: 'Electronic road toll rules are not among the CRA’s exclusions. They affect the RED cybersecurity requirements instead.',
      },
    ],
  },
};
